name: Deploy
on:
  push:
    branches: [main]
permissions: {}
jobs:
  build:
    uses: edlgg/edg-infra/.github/workflows/build-push.yml@main
    with:
      service: refigan
    permissions:
      id-token: write
      contents: read
