name: Deploy

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: edlgg/edg-infra/.github/workflows/build-push.yml@main
    with:
      service: refigan
      deploy: true
